---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linkerd-viz-psp
  namespace: {{.Values.namespace}}
  labels:
    {{.Values.extensionAnnotation}}: linkerd-viz
    namespace: {{.Values.namespace}}
roleRef:
  kind: Role
  name: linkerd-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: linkerd-tap
  namespace: {{.Values.namespace}}
- kind: ServiceAccount
  name: linkerd-web
  namespace: {{.Values.namespace}}
{{ if .Values.grafana.enabled -}}
- kind: ServiceAccount
  name: linkerd-grafana
  namespace: {{.Values.namespace}}
{{ end -}}
{{ if .Values.prometheus.enabled -}}
- kind: ServiceAccount
  name: linkerd-prometheus
  namespace: {{.Values.namespace}}
{{ end -}}
