# -- Set to false when installing in a custom namespace.
installNamespace: true
# Default values for tracing.

namespace: linkerd-jaeger

# -- Default nodeSelector section, See the
# [K8S documentation](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector) for more information
nodeSelector: &default_node_selector
  beta.kubernetes.io/os: linux

# -- Default tolerations section, See the
# [K8S documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)
# for more information
tolerations: &default_tolerations

collector:
  # -- Set to false to exclude collector installation
  enabled: true
  image:
    name: omnition/opencensus-collector
    version: 0.1.11
    pullPolicy: Always

  # -- NodeSelector section, See the
  # [K8S documentation](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector) for more information
  nodeSelector: *default_node_selector
  # -- Tolerations section, See the
  # [K8S documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)
  # for more information
  tolerations: *default_tolerations

  # -- address of the jaeger backend to send traces to
  jaegerAddr:

jaeger:
  # -- Set to false to exclude all-in-one Jaeger installation
  enabled: true
  image:
    name: jaegertracing/all-in-one
    version: 1.19.2
    pullPolicy: Always
  # -- NodeSelector section, See the
  # [K8S documentation](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector) for more information
  nodeSelector: *default_node_selector
  # -- Tolerations section, See the
  # [K8S documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)
  # for more information
  tolerations: *default_tolerations

linkerdVersion: &linkerd_version linkerdVersionValue

webhook:
  externalSecret: false
  # -- if empty, Helm will auto-generate these fields
  crtPEM: |

  keyPEM: |

  # -- if empty, Helm will auto-generate this field, unless externalSecret is set to true.
  caBundle: |

  # -- collector service address for the proxies to send trace data.
  # Points by default to the the linkerd-jaeger collector
  collectorSvcAddr: collector.linkerd-jaeger:55678
  # -- service account associated with the collector instance
  collectorSvcAccount: collector

  failurePolicy: Ignore
  image:
    name: cr.l5d.io/linkerd/jaeger-webhook
    version: *linkerd_version
    pullPolicy: IfNotPresent
  logLevel: info

  namespaceSelector:
    #matchExpressions:
    #- key: runlevel
    #  operator: NotIn
    #  values: ["0","1"]
  objectSelector:
    #matchLabels:
    #  foo: bar

  # -- NodeSelector section, See the
  # [K8S documentation](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector) for more information
  nodeSelector: *default_node_selector
  # -- Tolerations section, See the
  # [K8S documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)
  # for more information
  tolerations: *default_tolerations
